### ISSUE TITLE
No startingPoint should respect actual site instead of /sites

### ISSUE THREAD

**Issue by paavo** [tmsdev/Tms.Select#10]
If no `startingPoint` is set, the RootNode `/sites` is used as startingPoint. 
This leads to unwanted effects in a multi-site setup as linking and refernces always use the actual site as startingPoint. 
I can't find a way to set the `startingPoint` to the currently active site. 

Changing the RootNode to the actual site would fix the issue: https://github.com/tmsdev/Tms.Select/blob/master/Classes/DataSource/NodeDataDataSource.php#L103

@jobee we already discussed this in Slack ☝️

**Comment by jobee** [comment]
@paavo could you please test if the latest commit works for you?

**Comment by paavo** [comment]
Updating the package with composer to 1.3.1 didn't fixed the problem for me. 
Replacing NodeDataDataSource.php manually with the updated version works perfectly for me 👍 
Did you included the changes in Version 1.3.1 @jobee?

Thanks for the fix 👏

**Comment by jobee** [comment]
Yeah, I was asking to test `dev-master`. Glad it works for you, I'll tag version `1.4.0` now as this is kind of breaking.
