### ISSUE TITLE
Remove &nbsp; from label

### ISSUE THREAD

**Issue by jonnitto** [tmsdev/Tms.Select#9]
It can happen that a label has a `&nbsp;` in it. This should be removed or replaced.

**Comment by jonnitto** [comment]
<img width="294" alt="CleanShot 2021-12-31 at 19 05 54@2x" src="https://user-images.githubusercontent.com/4510166/147834997-3455231c-d943-4842-bf08-4c21218d793b.png">

**Comment by jobee** [comment]
Good catch. And it's not just about non-breaking spaces. By setting `labelPropertyName` to a property which uses ckeditor there can easily be other unwanted markup too. I'll make sure that the label is plain text only.
